Repository final-project-blazing-fox/user-profile-service, pull requests merged in 2021-09, with the labels that each got.

#7 Create github workflow for linter and testing
  .github/workflows/lint.yml
  .github/workflows/node.js.yml
  .husky/pre-commit
  .prettierignore
  package-lock.json
  package.json
  tests/api.test.js
Labels: enhancement

#8 Add additional github workflow, onboarding documentation, and monitoring badge
  .github/workflows/node.js.yml
  .husky/pre-commit
  .prettierignore
  ONBOARDING.md
  README.md
  package.json
Labels: documentation, enhancement

#9 Fix code coverage badge and documentation
  .github/workflows/lint.yml
  ONBOARDING.md
  README.md
Labels: bug

#14 fix: rest api
  .env-example
  .github/workflows/node.js.yml
  .husky/commit-msg
  .husky/pre-commit
  Procfile
  app.js
  bin/server.js
  config/config.js
  controllers/UserController.js
  helpers/bcrypt.js
  helpers/jwt.js
  middlewares/auth.js
  middlewares/errorHandler.js
  migrations/20210914164219-create-user.js
  models/index.js
  models/user.js
  package-lock.json
  package.json
  routes/routes.js
  seeders/20210914164406-userInitialSeeds.js
  seeders/userSeeds.json
  tests/api.test.js
Labels: enhancement
